#!/usr/bin/env python3
"""demos.py — the animated strips the README embeds.

    demo/weights.svg     one path, three pens
    demo/scanline.svg    the mask, at three pitches, rolling
    demo/motion.svg      five animations on a loop
    demo/colour.svg      mono, multi, and the wash
    demo/set.svg         a strip of the set, drawing itself on

A README on GitHub cannot run the package's stylesheets — there is no page for
them to live in, and a `<link>` inside an embedded SVG is stripped. So each of
these is ONE SELF-CONTAINED FILE: geometry lifted from dist/, plus an inline
<style> carrying the same rules swarnil-icons.css ships. GitHub serves them
through an <img>, where internal CSS and CSS animations do run and external
anything does not.

That means the CSS here is a COPY, and a copy is a thing that drifts. It is
worth it for one reason: a README that shows a static picture of a motion
system is a README that has to be believed, and one that plays it is not. The
copy is kept honest by being small — the rules below are the handful the demos
actually need, quoted rather than paraphrased, and regenerated by this script
rather than hand-maintained.

    python3 scripts/demos.py          (or `npm run build`, which chains it)

demo/ IS committed, unlike dist/ and site/, because README.md points at it on
the default branch and a gitignored file renders as a broken image.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIST = ROOT / 'dist'
OUT = ROOT / 'demo'

# The design system's signal red and its neutrals, as plain sRGB hex. The
# package authors these in oklch() reading --accent; an <img> has no design
# system to read and some renderers still choke on oklch(), so the demos carry
# the flattened value. Same colour, fewer assumptions.
INK_LIGHT, INK_DARK = '#1c1c22', '#e9e9ee'
DIM_LIGHT, DIM_DARK = '#6b6b78', '#9a9aa8'
ACCENT = '#e2593a'
SOFT_LIGHT, SOFT_DARK = '#f7ded7', '#3a221c'

CELL = 96          # one icon's box, in demo units
ICON = 48          # the icon drawn inside it
LABEL_Y = 78       # baseline for the caption under each icon

FONT = ("-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, "
        "Helvetica, Arial, sans-serif")


def geometry():
    data = json.loads((DIST / 'icons.json').read_text())
    return {i['name']: i for i in data['icons']}


ICONS = {}


def icon(name, x, y, *, stroke=1.5, cls='', size=ICON, style='', outer=''):
    """One icon, placed. The body is the same string dist/sprite.svg carries.

    TWO nested groups, and the nesting is load-bearing. The outer one places
    and scales; the inner one is what a style class goes on. They cannot be the
    same element, because CSS `transform` REPLACES the transform presentation
    attribute rather than composing with it — put `animation: spin` on the
    element carrying translate() and the first keyframe throws the translate
    away, dropping the icon onto the origin. Three of these strips did exactly
    that, stacked in the top-left corner, until they were split.

    `outer` is for the one thing that must NOT go on the inner group: a mask.
    Mask lengths resolve in the coordinate system of the element they are on,
    so a mask inside scale(2) is drawn at twice its stated pitch — a scanline
    demo that quietly disagrees with the package it is demonstrating. It goes
    on the placed group, where a px is a px, and it can share that element with
    the transform attribute safely because masking does not replace it the way
    a CSS transform does.

    Scaled by transform rather than by a nested <svg>, so the stroke scales
    with it — which is what a 48px icon in the real package does too, since the
    stroke is 1.5 USER units on a 24 grid and the browser scales user units.
    """
    k = size / 24
    inner = (f'<g'
             + (f' class="{cls}"' if cls else '')
             + (f' style="{style}"' if style else '')
             + f'>{ICONS[name]["body"]}</g>')
    return (f'<g transform="translate({x} {y}) scale({k})" stroke-width="{stroke}"'
            + (f' class="{outer}"' if outer else '')
            + f'>{inner}</g>')


def label(text, x, y=LABEL_Y, cls='cap'):
    return (f'<text x="{x}" y="{y}" class="{cls}" text-anchor="middle">'
            f'{text}</text>')


def doc(width, height, style, body, title):
    """The wrapper. `role="img"` plus a <title> so the strip is not silently
    blank to a screen reader — a README image with no text alternative is the
    one accessibility failure that is entirely the author's."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
            f'width="{width}" height="{height}" fill="none" role="img" '
            f'aria-label="{title}">'
            f'<title>{title}</title>'
            f'<style>{BASE}{style}</style>'
            f'{body}</svg>\n')


# The rules every strip needs: the two colours, the caption type, and the
# light/dark swap. prefers-color-scheme inside a standalone SVG follows the
# viewer's own setting, which is what GitHub's auto theme follows too.
BASE = f'''
svg {{ stroke: {INK_LIGHT}; fill: none; stroke-linecap: round; stroke-linejoin: round; }}
[fill="currentColor"] {{ fill: {INK_LIGHT}; stroke: none; }}
.cap {{ font: 500 12px {FONT}; fill: {DIM_LIGHT}; stroke: none; letter-spacing: .02em; }}
.cap--on {{ fill: {ACCENT}; }}
.accent {{ stroke: {ACCENT}; }}
.accent [fill="currentColor"] {{ fill: {ACCENT}; }}
@media (prefers-color-scheme: dark) {{
  svg {{ stroke: {INK_DARK}; }}
  [fill="currentColor"] {{ fill: {INK_DARK}; }}
  .cap {{ fill: {DIM_DARK}; }}
  .cap--on {{ fill: {ACCENT}; }}
  .accent {{ stroke: {ACCENT}; }}
  .accent [fill="currentColor"] {{ fill: {ACCENT}; }}
}}
@media (prefers-reduced-motion: reduce) {{
  * {{ animation: none !important; stroke-dasharray: none !important;
       stroke-dashoffset: 0 !important; opacity: 1 !important; }}
}}
'''


# ── the strips ────────────────────────────────────────────────────────────

def weights():
    """One geometry, three pens. The point is that nothing is redrawn, so the
    same icon is used three times rather than three similar ones."""
    rows = [('thin', 1, 'ic-thin'), ('regular', 1.5, 'ic-line'), ('bold', 2, 'ic-bold')]
    body = ''
    for n, (name, w, cls) in enumerate(rows):
        cx = CELL // 2 + n * CELL
        body += icon('capture', cx - ICON // 2, 12, stroke=w)
        body += label(f'{name} · {cls}', cx)
    return doc(CELL * 3, 96, '', body, 'The three weights: thin, regular and bold')


# The package's numbers, resolved against the size these are drawn at. One
# raster, and it is the same one in all three cells — what differs is what is
# done to it. max(1.2px, size/60): at the 72px these draw at, the floor is what
# wins, which is the whole point of the floor.
SCAN_PITCH = max(1.2, 72 / 60)
SCAN_DUTY = '65%'


def scanline():
    """One raster: still, rolling, and flickering.

    This is the demo that has to move to make its case — a still of a scanline
    at this pitch is indistinguishable from a slightly grubby icon, which is
    exactly the complaint that made the pitch this fine in the first place.

    Drawn at 72px rather than the 48 the other strips use, because the whole
    claim being made is "too fine to count" and a claim about fineness needs
    the room to be seen. The mask and the roll are the package's own rules
    quoted verbatim: a one-period gradient tiled by mask-size, scrolled exactly
    one pitch so the loop is seamless.
    """
    style = f'''
.scan {{
  -webkit-mask-image: linear-gradient(to bottom, #000 0 {SCAN_DUTY}, transparent {SCAN_DUTY} 100%);
          mask-image: linear-gradient(to bottom, #000 0 {SCAN_DUTY}, transparent {SCAN_DUTY} 100%);
  -webkit-mask-size: 100% {SCAN_PITCH:.3f}px; mask-size: 100% {SCAN_PITCH:.3f}px;
  -webkit-mask-repeat: repeat; mask-repeat: repeat;
}}
.roll {{ animation: roll 2.6s linear infinite; }}
@keyframes roll {{
  from {{ -webkit-mask-position: 0 0; mask-position: 0 0; }}
  to {{ -webkit-mask-position: 0 {SCAN_PITCH:.3f}px; mask-position: 0 {SCAN_PITCH:.3f}px; }}
}}
.flick {{ animation: roll 2.6s linear infinite, flick 5s steps(1, end) infinite; }}
@keyframes flick {{
  0%, 90%, 100% {{ opacity: 1; }} 91% {{ opacity: .45; }} 92% {{ opacity: 1; }}
  94% {{ opacity: .72; }} 95% {{ opacity: 1; }}
}}'''
    cells = [('ic-scan', 'scan'), ('+ ic-scan-roll', 'scan roll'),
             ('+ ic-flicker', 'scan flick')]
    wide = 128
    body = ''
    for n, (cap, cls) in enumerate(cells):
        cx = wide // 2 + n * wide
        body += icon('camera', cx - 36, 10, stroke=2, size=72, outer=f'{cls} accent')
        body += label(cap, cx, y=100)
    return doc(wide * 3, 118, style, body,
               'One scanline raster: still, rolling, and flickering')


def motion():
    """Five animations, all on loop. Every keyframe here is the one shipped in
    swarnil-icons-motion.css, at the same duration."""
    style = '''
.draw { stroke-dasharray: 1; animation: draw 2.4s cubic-bezier(.65,0,.35,1) infinite; }
@keyframes draw { 0%,4% { stroke-dashoffset: 1; } 46%,64% { stroke-dashoffset: 0; }
                  100% { stroke-dashoffset: -1; } }
.fade { animation: fade 1.8s cubic-bezier(.65,0,.35,1) infinite; }
@keyframes fade { 0%,100% { opacity: 1; } 50% { opacity: .3; } }
.pop { transform-origin: 12px 12px; animation: pop 2.6s ease-in-out infinite; }
@keyframes pop { 0%,70%,100% { transform: scale(1); } 78% { transform: scale(1.15); }
                 86% { transform: scale(.97); } 93% { transform: scale(1.04); } }
.spin { transform-origin: 12px 12px; animation: spin 1.4s linear infinite; }
@keyframes spin { from { transform: rotate(0); } to { transform: rotate(360deg); } }
.pulse { transform-origin: 12px 12px; animation: pulse 2s ease-in-out infinite; }
@keyframes pulse { 0%,100% { opacity: 1; transform: scale(1); }
                   50% { opacity: .65; transform: scale(1.08); } }
'''
    rows = [('draw', 'activity'), ('fade', 'eye'), ('pop', 'circle-check'),
            ('spin', 'refresh'), ('pulse', 'record')]
    body = ''
    for n, (cls, name) in enumerate(rows):
        cx = CELL // 2 + n * CELL
        body += icon(name, cx - ICON // 2, 12, cls=cls)
        body += label(f'ic-{cls}-loop', cx)
    return doc(CELL * 5, 96, style, body,
               'Five animations on a loop: draw, fade, pop, spin and pulse')


def colour():
    """Mono, the brand colour, and the three-colour mode.

    ic-multi works by INHERITANCE — the stroke takes the ink, `color` takes the
    primary, and the marks authored as fill="currentColor" pick it up — so it
    is reproduced here as exactly that and not as a hand-coloured copy.
    """
    style = f'''
.multi {{ stroke: {INK_LIGHT}; }}
.multi [fill="currentColor"] {{ fill: {ACCENT}; }}
.multi > *:not(:first-child) {{ stroke: {ACCENT}; }}
.wash {{ fill: {SOFT_LIGHT}; }}
@media (prefers-color-scheme: dark) {{
  .multi {{ stroke: {INK_DARK}; }}
  .wash {{ fill: {SOFT_DARK}; }}
}}
'''
    rows = [('mono', 'camera', '', ''), ('ic-primary', 'camera', 'accent', ''),
            ('ic-multi', 'camera', 'multi', ''),
            ('ic-multi-fill', 'camera', 'multi wash', '')]
    body = ''
    for n, (cap, name, cls, st) in enumerate(rows):
        cx = CELL // 2 + n * CELL
        body += icon(name, cx - ICON // 2, 12, cls=cls, style=st)
        body += label(cap, cx)
    return doc(CELL * 4, 96, style, body,
               'Mono, the brand colour, and the three-colour mode')


def strip():
    """The set drawing itself on, staggered. The header image."""
    names = ['capture', 'camera', 'aperture', 'live', 'waveform', 'compass',
             'rocket', 'italy', 'beach', 'relocation', 'sparkle', 'heart']
    style = '''
.d { stroke-dasharray: 1; animation: d 3.6s cubic-bezier(.65,0,.35,1) infinite; }
@keyframes d { 0%,6% { stroke-dashoffset: 1; } 40%,72% { stroke-dashoffset: 0; }
               100% { stroke-dashoffset: -1; } }
'''
    step = 66
    body = ''
    for n, name in enumerate(names):
        body += icon(name, 12 + n * step, 12, size=42, cls='d',
                     style=f'animation-delay: {n * 140}ms')
    return doc(12 + len(names) * step, 66, style, body,
               'A strip of the set drawing itself on')


BUILDERS = {'weights': weights, 'scanline': scanline, 'motion': motion,
            'colour': colour, 'set': strip}


def main():
    if not (DIST / 'icons.json').exists():
        print('dist/icons.json missing — run scripts/build.py first')
        return 1

    ICONS.update(geometry())
    OUT.mkdir(exist_ok=True)
    for name, build in BUILDERS.items():
        svg = build()
        # pathLength="1" is what makes the draw animation work without
        # JavaScript, and it is already stamped on the bodies in icons.json —
        # so it arrives here for free. Assert it rather than assume it: a demo
        # whose draw silently does nothing looks like a broken effect, not a
        # broken pipeline.
        if name in ('motion', 'set') and 'pathLength="1"' not in svg:
            print(f'  {name}: no pathLength in the geometry — draw will not animate')
        (OUT / f'{name}.svg').write_text(svg)

    print(f'wrote {len(BUILDERS)} README demos -> demo/')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
